version: '3'
networks:
  app_net:
volumes:
  dados:
services:
  db:
    image: postgres
    volumes:
      - dados:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  meu_app:
    build: ./app
    ports:
       - 8080:5000
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - db
